"""Tests for release note models.

TDD: Tests written FIRST before implementation.
Tests SQLModel definitions for ReleaseNote and UserReleaseNoteSeen.
"""

from datetime import UTC, datetime

import pytest

from app.models.release_note import ReleaseNote, UserReleaseNoteSeen


class TestReleaseNoteModel:
    """Tests for the ReleaseNote SQLModel."""

    def test_create_release_note(self):
        """Should create a ReleaseNote instance with required fields."""
        note = ReleaseNote(
            version="0.2.0",
            user_notes="Nuove funzionalità disponibili!",
            technical_notes="Added versioning system.",
        )
        assert note.version == "0.2.0"
        assert note.user_notes == "Nuove funzionalità disponibili!"
        assert note.technical_notes == "Added versioning system."

    def test_version_field_is_string(self):
        """Should store version as a string."""
        note = ReleaseNote(
            version="1.0.0",
            user_notes="Prima release stabile.",
            technical_notes="Stable release.",
        )
        assert isinstance(note.version, str)

    def test_table_name(self):
        """Should use 'release_notes' as the table name."""
        assert ReleaseNote.__tablename__ == "release_notes"


class TestUserReleaseNoteSeenModel:
    """Tests for the UserReleaseNoteSeen SQLModel."""

    def test_create_seen_record(self):
        """Should create a UserReleaseNoteSeen instance."""
        seen = UserReleaseNoteSeen(
            user_id=1,
            release_note_id=1,
        )
        assert seen.user_id == 1
        assert seen.release_note_id == 1

    def test_table_name(self):
        """Should use 'user_release_note_seen' as the table name."""
        assert UserReleaseNoteSeen.__tablename__ == "user_release_note_seen"

    def test_default_id_is_none(self):
        """Should default id to None (auto-generated by DB)."""
        seen = UserReleaseNoteSeen(user_id=1, release_note_id=1)
        assert seen.id is None
