"""phase_4_regional_tax_models

Revision ID: 9c4322e06e4d
Revises: 18759d179eec
Create Date: 2025-11-28 14:59:07.174211

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "9c4322e06e4d"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "18759d179eec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regioni",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("codice_istat", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("is_autonomous", sa.Boolean(), nullable=False),
        sa.Column("has_special_statute", sa.Boolean(), nullable=False),
        sa.Column("area_kmq", sa.Integer(), nullable=True),
        sa.Column("popolazione", sa.Integer(), nullable=True),
        sa.Column("capoluogo", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nome"),
    )
    op.create_index(op.f("ix_regioni_codice_istat"), "regioni", ["codice_istat"], unique=True)
    op.create_table(
        "comuni",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("codice_istat", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("provincia", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("regione_id", sa.Uuid(), nullable=False),
        sa.Column("cap_codes", postgresql.ARRAY(sa.String(length=5)), nullable=False),
        sa.Column("is_capoluogo", sa.Boolean(), nullable=False),
        sa.Column("is_capoluogo_provincia", sa.Boolean(), nullable=False),
        sa.Column("is_metropolitan_city", sa.Boolean(), nullable=False),
        sa.Column("popolazione", sa.Integer(), nullable=True),
        sa.Column("area_kmq", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("densita_abitativa", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("latitudine", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitudine", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("altitudine", sa.Integer(), nullable=True),
        sa.Column("sindaco", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("telefono", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("pec", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("sito_web", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["regione_id"],
            ["regioni.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comuni_cap_search", "comuni", ["cap_codes"], unique=False)
    op.create_index("idx_comuni_popolazione", "comuni", ["popolazione"], unique=False)
    op.create_index("idx_comuni_provincia_nome", "comuni", ["provincia", "nome"], unique=False)
    op.create_index(op.f("ix_comuni_cap_codes"), "comuni", ["cap_codes"], unique=False)
    op.create_index(op.f("ix_comuni_codice_istat"), "comuni", ["codice_istat"], unique=True)
    op.create_index(op.f("ix_comuni_provincia"), "comuni", ["provincia"], unique=False)
    op.create_table(
        "regional_tax_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("regione_id", sa.Uuid(), nullable=False),
        sa.Column("tax_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("rate_standard", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("rate_banks", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_insurance", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_agriculture", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_cooperatives", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("minimum_tax", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("maximum_tax", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exemption_threshold", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("calculation_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("legislative_reference", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["regione_id"],
            ["regioni.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("regione_id", "tax_type", "valid_from", name="uq_regional_tax_rate_period"),
    )
    op.create_index(
        "idx_regional_tax_rates_lookup",
        "regional_tax_rates",
        ["regione_id", "tax_type", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_index(op.f("ix_regional_tax_rates_tax_type"), "regional_tax_rates", ["tax_type"], unique=False)
    op.create_index(op.f("ix_regional_tax_rates_valid_from"), "regional_tax_rates", ["valid_from"], unique=False)
    op.create_index(op.f("ix_regional_tax_rates_valid_to"), "regional_tax_rates", ["valid_to"], unique=False)
    op.create_table(
        "comunal_tax_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("comune_id", sa.Uuid(), nullable=False),
        sa.Column("tax_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("rate_prima_casa", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_altri_immobili", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_commerciale", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_industriale", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rate_agricolo", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("esenzione_prima_casa", sa.Boolean(), nullable=False),
        sa.Column("esenzione_giovani_coppie", sa.Boolean(), nullable=True),
        sa.Column("esenzione_over_65", sa.Boolean(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("detrazioni", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("soglie", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("maggiorazioni", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("agevolazioni", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delibera_comunale", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("data_delibera", sa.Date(), nullable=True),
        sa.Column("legislative_reference", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comune_id"],
            ["comuni.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comune_id", "tax_type", "valid_from", name="uq_comunal_tax_rate_period"),
    )
    op.create_index(
        "idx_comunal_tax_rates_lookup",
        "comunal_tax_rates",
        ["comune_id", "tax_type", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_index(op.f("ix_comunal_tax_rates_tax_type"), "comunal_tax_rates", ["tax_type"], unique=False)
    op.create_index(op.f("ix_comunal_tax_rates_valid_from"), "comunal_tax_rates", ["valid_from"], unique=False)
    op.create_index(op.f("ix_comunal_tax_rates_valid_to"), "comunal_tax_rates", ["valid_to"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comunal_tax_rates_valid_to"), table_name="comunal_tax_rates")
    op.drop_index(op.f("ix_comunal_tax_rates_valid_from"), table_name="comunal_tax_rates")
    op.drop_index(op.f("ix_comunal_tax_rates_tax_type"), table_name="comunal_tax_rates")
    op.drop_index("idx_comunal_tax_rates_lookup", table_name="comunal_tax_rates")
    op.drop_table("comunal_tax_rates")
    op.drop_index(op.f("ix_regional_tax_rates_valid_to"), table_name="regional_tax_rates")
    op.drop_index(op.f("ix_regional_tax_rates_valid_from"), table_name="regional_tax_rates")
    op.drop_index(op.f("ix_regional_tax_rates_tax_type"), table_name="regional_tax_rates")
    op.drop_index("idx_regional_tax_rates_lookup", table_name="regional_tax_rates")
    op.drop_table("regional_tax_rates")
    op.drop_index(op.f("ix_comuni_provincia"), table_name="comuni")
    op.drop_index(op.f("ix_comuni_codice_istat"), table_name="comuni")
    op.drop_index(op.f("ix_comuni_cap_codes"), table_name="comuni")
    op.drop_index("idx_comuni_provincia_nome", table_name="comuni")
    op.drop_index("idx_comuni_popolazione", table_name="comuni")
    op.drop_index("idx_comuni_cap_search", table_name="comuni")
    op.drop_table("comuni")
    op.drop_index(op.f("ix_regioni_codice_istat"), table_name="regioni")
    op.drop_table("regioni")
    # ### end Alembic commands ###
