apiVersion: 1

# Delete existing notification channels if they exist
deleteNotificationChannels:
  - name: email-alerts
  - name: slack-alerts
  - name: webhook-alerts

# Create new notification channels
notificationChannels:
  # Email notifications for critical alerts
  - name: email-alerts
    type: email
    uid: email-uid
    isDefault: true
    settings:
      addresses: "admin@pratikoai.com;alerts@pratikoai.com"
      subject: "[PratikoAI] {{ .GroupLabels.alertname }} - {{ .Status }}"
      body: |
        <h2>PratikoAI Alert: {{ .GroupLabels.alertname }}</h2>
        
        <p><strong>Status:</strong> {{ .Status }}</p>
        <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
        <p><strong>Team:</strong> {{ .GroupLabels.team }}</p>
        <p><strong>Category:</strong> {{ .GroupLabels.category }}</p>
        
        <h3>Alert Details</h3>
        {{ range .Alerts }}
        <div style="margin: 10px 0; padding: 10px; border-left: 4px solid #ff6b6b;">
          <p><strong>{{ .Annotations.summary }}</strong></p>
          <p>{{ .Annotations.description }}</p>
          {{ if .Annotations.runbook_url }}
          <p><a href="{{ .Annotations.runbook_url }}">📖 Runbook</a></p>
          {{ end }}
          <p><small>Started: {{ .StartsAt }}</small></p>
        </div>
        {{ end }}
        
        <hr>
        <p><small>Generated by PratikoAI Monitoring System</small></p>
    sendResolved: true

  # Slack notifications for team channels
  - name: slack-alerts
    type: slack
    uid: slack-uid
    settings:
      url: "${SLACK_WEBHOOK_URL}"
      channel: "#pratikoai-alerts"
      username: "PratikoAI Monitor"
      title: "{{ .GroupLabels.alertname }} - {{ .Status }}"
      text: |
        {{ range .Alerts }}
        *{{ .Annotations.summary }}*
        {{ .Annotations.description }}
        
        *Team:* {{ .Labels.team }}
        *Severity:* {{ .Labels.severity }}
        *Category:* {{ .Labels.category }}
        {{ if .Annotations.runbook_url }}
        📖 <{{ .Annotations.runbook_url }}|Runbook>
        {{ end }}
        {{ end }}
      color: |
        {{ if eq .Status "firing" }}
          {{ if eq .GroupLabels.severity "critical" }}danger{{ else }}warning{{ end }}
        {{ else }}good{{ end }}
      iconEmoji: ":rotating_light:"
    sendResolved: true

  # Webhook for custom integrations
  - name: webhook-alerts
    type: webhook
    uid: webhook-uid
    settings:
      url: "${WEBHOOK_URL:-http://localhost:3001/alerts}"
      httpMethod: POST
      maxAlerts: 0
      title: "PratikoAI Alert"
      body: |
        {
          "receiver": "{{ .Receiver }}",
          "status": "{{ .Status }}",
          "alerts": [
            {{ range $i, $alert := .Alerts }}
            {{ if $i }},{{ end }}
            {
              "status": "{{ $alert.Status }}",
              "labels": {
                {{ range $k, $v := $alert.Labels }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "alertname": "{{ $alert.Labels.alertname }}"
              },
              "annotations": {
                {{ range $k, $v := $alert.Annotations }}
                "{{ $k }}": "{{ $v }}",
                {{ end }}
                "summary": "{{ $alert.Annotations.summary }}"
              },
              "startsAt": "{{ $alert.StartsAt }}",
              "endsAt": "{{ $alert.EndsAt }}",
              "generatorURL": "{{ $alert.GeneratorURL }}"
            }
            {{ end }}
          ],
          "groupLabels": {
            {{ range $k, $v := .GroupLabels }}
            "{{ $k }}": "{{ $v }}",
            {{ end }}
            "alertname": "{{ .GroupLabels.alertname }}"
          },
          "commonLabels": {
            {{ range $k, $v := .CommonLabels }}
            "{{ $k }}": "{{ $v }}",
            {{ end }}
            "alertname": "{{ .CommonLabels.alertname }}"
          }
        }
    sendResolved: true

  # PagerDuty for critical production issues
  - name: pagerduty-critical
    type: pagerduty
    uid: pagerduty-uid
    settings:
      integrationKey: "${PAGERDUTY_INTEGRATION_KEY}"
      severity: "{{ .GroupLabels.severity }}"
      component: "PratikoAI"
      group: "{{ .GroupLabels.team }}"
      class: "{{ .GroupLabels.category }}"
      customDetails: |
        {
          "alert_count": {{ len .Alerts }},
          "alerts": [
            {{ range $i, $alert := .Alerts }}
            {{ if $i }},{{ end }}
            {
              "summary": "{{ $alert.Annotations.summary }}",
              "description": "{{ $alert.Annotations.description }}",
              "runbook_url": "{{ $alert.Annotations.runbook_url }}"
            }
            {{ end }}
          ]
        }
    sendResolved: true