# PratikoAI MCP Server Security Configuration
# Comprehensive security settings for all environments

security:
  # Authentication and Authorization
  authentication:
    method: "oauth2_jwt"  # oauth2_jwt, basic_auth, api_key
    jwt:
      issuer: "https://auth.pratiko.ai"
      audience: "pratiko-mcp-api"
      algorithm: "RS256"
      public_key_url: "https://auth.pratiko.ai/.well-known/jwks.json"
      token_expiry: 3600  # seconds
      refresh_token_expiry: 86400  # 24 hours
      
    oauth2:
      provider: "auth0"  # auth0, cognito, keycloak
      client_id: "${OAUTH2_CLIENT_ID}"
      client_secret: "${OAUTH2_CLIENT_SECRET}"
      discovery_url: "https://pratiko.auth0.com/.well-known/openid_configuration"
      scopes: ["openid", "profile", "email", "mcp:read", "mcp:write"]

  # Role-Based Access Control (RBAC)
  rbac:
    enabled: true
    roles:
      admin:
        permissions:
          - "mcp:*"
          - "admin:*"
          - "monitor:*"
        environments: ["development", "staging", "production"]
        
      developer:
        permissions:
          - "mcp:read"
          - "mcp:write"
          - "monitor:read"
        environments: ["development", "staging"]
        
      operator:
        permissions:
          - "mcp:read"
          - "mcp:execute"
          - "monitor:read"
        environments: ["staging", "production"]
        
      viewer:
        permissions:
          - "mcp:read"
          - "monitor:read"
        environments: ["development", "staging", "production"]

  # Network Security
  network:
    tls:
      enabled: true
      min_version: "1.3"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_CHACHA20_POLY1305_SHA256"
      certificate_path: "/app/certs/server.crt"
      private_key_path: "/app/certs/server.key"
      ca_certificate_path: "/app/certs/ca.crt"
      
    cors:
      enabled: true
      allowed_origins:
        development: ["http://localhost:3000", "http://localhost:8080"]
        staging: ["https://staging.pratiko.ai", "https://staging-app.pratiko.ai"]
        production: ["https://pratiko.ai", "https://app.pratiko.ai"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Authorization", "Content-Type", "X-Requested-With"]
      exposed_headers: ["X-Request-ID", "X-Response-Time"]
      credentials: true
      max_age: 86400
      
    rate_limiting:
      enabled: true
      global_limit: 10000  # requests per hour
      per_ip_limit: 1000   # requests per hour
      per_user_limit: 5000 # requests per hour
      burst_size: 100      # burst requests
      window_size: 3600    # window in seconds
      
    firewall:
      enabled: true
      allowed_ips:
        development: ["0.0.0.0/0"]  # Allow all for development
        staging: 
          - "10.0.0.0/16"           # Internal VPC
          - "203.0.113.0/24"        # Office network
        production:
          - "10.0.0.0/16"           # Internal VPC
          - "203.0.113.0/24"        # Office network
          - "198.51.100.0/24"       # Partner network
      blocked_countries: ["CN", "RU", "KP", "IR"]  # Geo-blocking

  # Input Validation and Sanitization
  input_validation:
    enabled: true
    max_request_size: "10MB"
    max_json_depth: 10
    max_array_length: 1000
    sanitize_html: true
    validate_schemas: true
    
    content_security:
      block_file_uploads: false
      allowed_file_types: [".pdf", ".txt", ".json", ".yaml"]
      max_file_size: "5MB"
      scan_uploads: true  # Virus scanning
      
    sql_injection_protection: true
    xss_protection: true
    csrf_protection: true

  # Data Protection
  data_protection:
    encryption_at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation_days: 90
      
    encryption_in_transit:
      enabled: true
      force_https: true
      hsts_enabled: true
      hsts_max_age: 31536000
      
    pii_protection:
      enabled: true
      mask_sensitive_data: true
      anonymize_logs: true
      retention_period_days: 365
      
    gdpr_compliance:
      enabled: true
      data_subject_rights: true
      consent_management: true
      breach_notification: true

  # Session Management
  session:
    secure: true
    http_only: true
    same_site: "strict"
    max_age: 3600  # 1 hour
    idle_timeout: 1800  # 30 minutes
    concurrent_sessions: 5
    session_fixation_protection: true

  # Audit and Logging
  audit:
    enabled: true
    log_level: "INFO"  # DEBUG, INFO, WARN, ERROR
    events:
      - "authentication"
      - "authorization"
      - "data_access"
      - "configuration_changes"
      - "administrative_actions"
      - "security_violations"
      
    destinations:
      - type: "file"
        path: "/var/log/audit/mcp-audit.log"
        rotation: "daily"
        retention_days: 90
        
      - type: "syslog"
        server: "syslog.pratiko.ai:514"
        protocol: "tcp"
        format: "json"
        
      - type: "elasticsearch"
        url: "https://elasticsearch.pratiko.ai:9200"
        index: "mcp-audit-logs"
        
    compliance:
      sox: true
      pci_dss: false
      hipaa: false
      iso27001: true

# Environment-specific security configurations
environments:
  development:
    security:
      authentication:
        jwt:
          token_expiry: 86400  # 24 hours for development
        require_mfa: false
      network:
        tls:
          enabled: true  # Still use TLS in development
          skip_verify: true  # Allow self-signed certificates
        rate_limiting:
          global_limit: 50000  # Higher limits for development
          per_ip_limit: 5000
      audit:
        log_level: "DEBUG"
        
  staging:
    security:
      authentication:
        require_mfa: true
      network:
        tls:
          skip_verify: false
        rate_limiting:
          global_limit: 20000
          per_ip_limit: 2000
      audit:
        log_level: "INFO"
        
  production:
    security:
      authentication:
        require_mfa: true
        require_certificate: true
      network:
        tls:
          skip_verify: false
          require_client_cert: true
        rate_limiting:
          global_limit: 10000
          per_ip_limit: 1000
        firewall:
          strict_mode: true
      audit:
        log_level: "INFO"
        real_time_alerts: true

# Security monitoring and alerting
monitoring:
  security_events:
    enabled: true
    real_time_detection: true
    
    alerts:
      - name: "failed_authentication"
        threshold: 5
        window: 300  # 5 minutes
        severity: "warning"
        
      - name: "unusual_access_pattern"
        threshold: 3
        window: 60   # 1 minute
        severity: "critical"
        
      - name: "privilege_escalation"
        threshold: 1
        window: 0    # immediate
        severity: "critical"
        
      - name: "data_exfiltration"
        threshold: 1
        window: 0    # immediate
        severity: "critical"
        
    integrations:
      slack:
        webhook_url: "${SECURITY_SLACK_WEBHOOK}"
        channel: "#security-alerts"
        
      pagerduty:
        integration_key: "${PAGERDUTY_SECURITY_KEY}"
        
      email:
        smtp_server: "smtp.pratiko.ai:587"
        recipients: ["security@pratiko.ai", "ops@pratiko.ai"]

# Security hardening settings
hardening:
  server:
    disable_server_header: true
    disable_x_powered_by: true
    enable_security_headers: true
    
    security_headers:
      strict_transport_security: "max-age=31536000; includeSubDomains"
      content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'"
      x_frame_options: "DENY"
      x_content_type_options: "nosniff"
      x_xss_protection: "1; mode=block"
      referrer_policy: "strict-origin-when-cross-origin"
      
  database:
    connection_encryption: true
    query_logging: false  # Disable to prevent sensitive data in logs
    prepared_statements: true
    connection_pooling: true
    max_connections: 100
    
  redis:
    auth_required: true
    connection_encryption: true
    disable_dangerous_commands: true
    
  kubernetes:
    pod_security_context:
      run_as_non_root: true
      run_as_user: 10001
      run_as_group: 10001
      read_only_root_filesystem: true
      
    network_policies:
      enabled: true
      default_deny: true
      
    secrets_management:
      external_secrets: true
      vault_integration: true
      auto_rotation: true

# Compliance and certifications
compliance:
  frameworks:
    - "SOC2_TYPE2"
    - "ISO27001"
    - "GDPR"
    - "CCPA"
    
  requirements:
    data_residency: "US"  # US, EU, APAC
    retention_policies: true
    right_to_deletion: true
    data_portability: true
    
  reporting:
    enabled: true
    frequency: "monthly"
    recipients: ["compliance@pratiko.ai", "legal@pratiko.ai"]